### ISSUE TITLE
RDNode longTermScienceTech nodeName may be not as intended

### ISSUE THREAD

**Issue by PadroneSF** [post-kerbin-mining-corporation/CommunityTechTree#57]
Extremely low impact.  Issue  is more of a housekeeping item than a functionality item.

For RDNode longTermScienceTech the nodeName is "CommunityTechTree/UI/ctt_icon_longTermScienceTech".

The other nodes seem to follow a convention that would lead to the name being "ct_longTermScienceTech".

**Comment by ChrisAdderley** [comment]
This actually also included a broken link to the icon. Sometimes I fix things! :D
